# Generated by Django 4.1.7 on 2023-04-04 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0002_customuser_enrolled_courses"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="enrolled_courses",
            new_name="applications",
        ),
    ]
