# Generated by Django 4.1.7 on 2023-04-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("login", "0003_rename_enrolled_courses_customuser_applications"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="eagle_id",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="customuser",
            name="major",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="year",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
