# Generated by Django 4.1.7 on 2023-04-21 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=255)),
                ('last_name', models.CharField(default=None, max_length=255)),
                ('eagle_id', models.CharField(default=None, max_length=255)),
                ('grad', models.CharField(choices=[('--', '--'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default='', max_length=50)),
                ('past_course', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=50)),
                ('grade', models.CharField(choices=[('--', '--'), ('a', 'A'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('c+', 'C+'), ('c', 'C'), ('c-', 'C-'), ('d+', 'D+'), ('d', 'D'), ('d-', 'D-'), ('f', 'F'), ('n/a', 'N/A')], default='', max_length=50)),
                ('hours', models.DecimalField(decimal_places=0, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_courses', models.CharField(default=None, max_length=800)),
                ('misc_information', models.CharField(default=None, max_length=800)),
            ],
        ),
    ]
