# Generated by Django 4.1.7 on 2023-03-19 04:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='course_title',
        ),
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.AddField(
            model_name='application',
            name='grade',
            field=models.CharField(choices=[('a', 'A'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('c+', 'C+'), ('c', 'C'), ('c-', 'C-'), ('d+', 'D+'), ('d', 'D'), ('d-', 'D-'), ('f', 'F'), ('n/a', 'N/A')], default='Select', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='hours',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(2, 2)]),
        ),
        migrations.AddField(
            model_name='application',
            name='misc_information',
            field=models.CharField(default='Enter text', max_length=800),
        ),
        migrations.AddField(
            model_name='application',
            name='other_courses',
            field=models.CharField(default='Enter text', max_length=800),
        ),
        migrations.AddField(
            model_name='application',
            name='past_course',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='Select', max_length=50),
        ),
    ]
