# Generated by Django 4.1.7 on 2023-04-04 16:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='course_title',
        ),
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
        migrations.AddField(
            model_name='application',
            name='eagle_id',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='first_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='grad',
            field=models.CharField(choices=[('--', '--'), ('2023', '2023'), ('2024', '2024'), ('2025', '2025'), ('2026', '2026')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='grade',
            field=models.CharField(choices=[('--', '--'), ('a', 'A'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('c+', 'C+'), ('c', 'C'), ('c-', 'C-'), ('d+', 'D+'), ('d', 'D'), ('d-', 'D-'), ('f', 'F'), ('n/a', 'N/A')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='application',
            name='hours',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='application',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='misc_information',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AddField(
            model_name='application',
            name='other_courses',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AddField(
            model_name='application',
            name='past_course',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=50),
        ),
    ]
