# Generated by Django 3.2.18 on 2023-04-21 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_auto_20230421_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='course_number',
        ),
        migrations.RemoveField(
            model_name='application',
            name='description',
        ),
    ]
