# Generated by Django 4.1.7 on 2023-03-19 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_application_course_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='grade',
            field=models.CharField(choices=[('a', 'A'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('c+', 'C+'), ('c', 'C'), ('c-', 'C-'), ('d+', 'D+'), ('d', 'D'), ('d-', 'D-'), ('f', 'F'), ('n/a', 'N/A')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='misc_information',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_courses',
            field=models.CharField(default='', max_length=800),
        ),
        migrations.AlterField(
            model_name='application',
            name='past_course',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=50),
        ),
    ]
