# Generated by Django 4.1.7 on 2023-03-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_application_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='misc_information',
            field=models.CharField(default=None, max_length=800),
        ),
        migrations.AlterField(
            model_name='application',
            name='other_courses',
            field=models.CharField(default=None, max_length=800),
        ),
    ]
