# Generated by Django 4.1.7 on 2023-03-19 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_application_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='grade',
            field=models.CharField(choices=[('', ''), ('a', 'A'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('c+', 'C+'), ('c', 'C'), ('c-', 'C-'), ('d+', 'D+'), ('d', 'D'), ('d-', 'D-'), ('f', 'F'), ('n/a', 'N/A')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='hours',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.DecimalValidator(3, 2)]),
        ),
        migrations.AlterField(
            model_name='application',
            name='past_course',
            field=models.CharField(choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], default='', max_length=50),
        ),
    ]
