# Generated by Django 4.1.7 on 2023-05-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0007_application_is_approved"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="student_response",
            field=models.CharField(
                choices=[("P", "Pending"), ("A", "Accepted"), ("D", "Declined")],
                default="P",
                max_length=1,
            ),
        ),
    ]
