# Generated by Django 4.1.7 on 2023-03-19 05:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_application_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hours',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.DecimalValidator(2, 2)]),
        ),
    ]
