# Generated by Django 4.1.7 on 2023-05-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_application_student_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
