# Generated by Django 4.1.7 on 2023-03-19 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_alter_application_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
