# Generated by Django 4.1.7 on 2023-03-19 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_alter_application_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='past_course',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=50),
        ),
    ]
