# Generated by Django 4.1.7 on 2023-03-19 06:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_alter_application_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='hours',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
