# Generated by Django 4.1.7 on 2023-03-19 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_application_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='grade',
            field=models.CharField(choices=[('--', '--'), ('a', 'A'), ('a-', 'A-'), ('b+', 'B+'), ('b-', 'B-'), ('c+', 'C+'), ('c', 'C'), ('c-', 'C-'), ('d+', 'D+'), ('d', 'D'), ('d-', 'D-'), ('f', 'F'), ('n/a', 'N/A')], default='', max_length=50),
        ),
    ]
