# Generated by Django 4.1.7 on 2023-03-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_application_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='misc_information',
            field=models.CharField(default='Enter text', max_length=800),
        ),
    ]
