# Generated by Django 4.1.7 on 2023-03-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_application_misc_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='misc_information',
            field=models.CharField(default=None, max_length=800),
        ),
    ]
