# Generated by Django 4.0.10 on 2023-03-20 01:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstructorAddCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_number', models.CharField(max_length=255)),
                ('course_instructor', models.CharField(max_length=255)),
                ('course_description', models.CharField(max_length=255)),
                ('has_discussion', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=50)),
                ('graded_meeting', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], default='', max_length=50)),
                ('num_hours', models.DecimalField(decimal_places=0, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('other_info', models.CharField(default=None, max_length=800)),
            ],
        ),
    ]
