# Generated by Django 3.2.18 on 2023-03-21 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstructorAddCourse', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructoraddcourse',
            old_name='num_hours',
            new_name='num_ta_needed',
        ),
        migrations.AddField(
            model_name='instructoraddcourse',
            name='office_hours',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='instructoraddcourse',
            name='total_time_commitment',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
