# Generated by Django 4.1.7 on 2023-04-03 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InstructorAddCourse', '0002_auto_20230321_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructoraddcourse',
            name='course_description',
            field=models.CharField(max_length=800),
        ),
    ]
