# Generated by Django 4.1.7 on 2023-04-04 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InstructorAddCourse", "0003_alter_instructoraddcourse_course_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="instructoraddcourse",
            name="curr_num_ta",
            field=models.IntegerField(default=0),
        ),
    ]
